
title: drno
email: alexanortega@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  When you have nothing to do, do something, research, read or have fun, it's the same.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

twitter_username: alexcott3
github_username:  alexcotte

# Build settings
theme: minima
plugins:
  - jekyll-feed
gems:
  - jekyll-paginate
  - jekyll-gist
exclude: [node_modules, README.md]
keep_files: [images]
sass:
    style: compressed
